"""Initial schema

Revision ID: 001_initial
Revises: 
Create Date: 2026-03-11 00:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create accounts table
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ig_username', sa.String(length=50), nullable=False),
    sa.Column('session_file', sa.String(length=255), nullable=True),
    sa.Column('proxy_id', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Integer(), server_default='100', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False,
              comment='active | quarantine | banned'),
    sa.Column('country', sa.String(length=10), server_default='IN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_ig_username'), 'accounts', ['ig_username'], unique=True)
    
    # Create proxies table
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False,
              comment='active | cooling | degraded | retired'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxies_country'), 'proxies', ['country'], unique=False)
    
    # Create reels table
    op.create_table('reels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('media_id', sa.String(length=100), nullable=True),
    sa.Column('creator_username', sa.String(length=50), nullable=True),
    sa.Column('creator_user_id', sa.BigInteger(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('follow_status', sa.String(length=30), nullable=True,
              comment='skipped | followed | already_following | private_pending'),
    sa.Column('followed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('comment_posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_status', sa.String(length=30), server_default='pending', nullable=False,
              comment='pending | follow_pending | commenting | completed | failed | challenge_pause'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reels_url'), 'reels', ['url'], unique=True)
    op.create_index(op.f('ix_reels_job_status'), 'reels', ['job_status'], unique=False)
    
    # Create follows table
    op.create_table('follows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_username', sa.String(length=50), nullable=True),
    sa.Column('followed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_back', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('follow_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follows_account_id'), 'follows', ['account_id'], unique=False)
    
    # Create dm_messages table
    op.create_table('dm_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reel_id', sa.Integer(), nullable=True),
    sa.Column('creator_user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('cta_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cta_confidence', sa.Float(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_messages_reel_id'), 'dm_messages', ['reel_id'], unique=False)
    op.create_index(op.f('ix_dm_messages_creator_user_id'), 'dm_messages', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_dm_messages_message_id'), 'dm_messages', ['message_id'], unique=True)
    
    # Create extracted_links table
    op.create_table('extracted_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dm_message_id', sa.Integer(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('redirect_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=20), nullable=True,
              comment='requests | playwright'),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('exported_to_excel', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['dm_message_id'], ['dm_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_links_dm_message_id'), 'extracted_links', ['dm_message_id'], unique=False)
    
    # Create task_log table
    op.create_table('task_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('reel_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_log_task_id'), 'task_log', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_log_account_id'), 'task_log', ['account_id'], unique=False)
    
    # Add foreign key constraint for accounts.proxy_id
    op.create_foreign_key(
        'fk_accounts_proxy_id',
        'accounts', 'proxies',
        ['proxy_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_accounts_proxy_id', 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_task_log_account_id'), table_name='task_log')
    op.drop_index(op.f('ix_task_log_task_id'), table_name='task_log')
    op.drop_table('task_log')
    op.drop_index(op.f('ix_extracted_links_dm_message_id'), table_name='extracted_links')
    op.drop_table('extracted_links')
    op.drop_index(op.f('ix_dm_messages_message_id'), table_name='dm_messages')
    op.drop_index(op.f('ix_dm_messages_creator_user_id'), table_name='dm_messages')
    op.drop_index(op.f('ix_dm_messages_reel_id'), table_name='dm_messages')
    op.drop_table('dm_messages')
    op.drop_index(op.f('ix_follows_account_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_reels_job_status'), table_name='reels')
    op.drop_index(op.f('ix_reels_url'), table_name='reels')
    op.drop_table('reels')
    op.drop_index(op.f('ix_proxies_country'), table_name='proxies')
    op.drop_table('proxies')
    op.drop_index(op.f('ix_accounts_ig_username'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
